### ISSUE TITLE
[Lv.2 Styled-Components] 질문 및 코드 리뷰 요청 - 김한솔

### ISSUE THREAD

**Issue by hansololiviakim** [Shinheeje/react-styled-component2#10]
# :question: Review
### **이번 과제에서 중점을 둔 사항**
* 버튼을 구현할 때 여러 곳에서 props 키워드에 따라 다양한 버튼을 가져올 수 있도록 구현했습니다.

<br/>

### **질의사항**
**1.**
버튼들이 있는 Buttons.jsx 에서 휴먼 에러를 줄이기 위해 단어들을 배열에 넣고 배열의 인덱스를 props로 내려주었는데 이렇게 하는게 오히려 불편한 방법일까요?

그리고 지금과 같이 버튼을 컴포넌트화해서 사용하는 상황에서 프로젝트 규모가 커졌을 때는 어떻게 props를 내려주는지 궁금합니다.

<br/>

**2.**
셀렉트 영역 구현 시 셀렉트 박스(구현은 ul 태그로 진행했습니다) 외부의 요소를 클릭했을 때도 셀렉트 리스트가 닫히도록 아래와 같이 구현했습니다.

```javascript
  const selectWrapRef = useRef();
  useEffect(() => {
    const clickListOutside = (e) => {
      if (selectWrapRef.current && !selectWrapRef.current.contains(e.target)) {
        toggleShowList();
      }
    };
    document.addEventListener('mousedown', clickListOutside);
    return () => {
      document.removeEventListener('mousedown', clickListOutside);
    };
  }, []);
```

DOM을 직접적으로 조작하는 방법은 좋지 않다고 들었는데 현업에서도 이러한 방법을 사용하는지 다른 방법을 사용하는게 좋을지 궁금합니다.

<br/>

**3.** 
리액트에서 숫자 세자리마다 `,` 를 찍어 사용자에게 보여줄 때 useState로는 toLocaleString을 걸고, DB에 데이터를 저장할 때는 replace 등으로 `,` 를 떼고 저장하는 편인지 아니면 111,111,111 이런 형식으로 DB에 저장하는 편인지 궁금합니다!

<br/>

**4.**
저는 아직 제 코드에 대해 객관적인 시각으로 보는게 어려워서 어느 부분은 어떤 방법을 권장하는지, 코드 작성법 등에 대해 기술매니저님 시각으로 본 전체 코드에 대한 자세한 리뷰를 듣고 싶습니다.

<br/><br/>

감사합니다.

**Comment by WooMinGy** [comment]
1. 휴면 에러를 줄이기 위해 배열을 사용했지만 한눈에 봤을 때 숫자를 잘못 칠 수도 있기 때문에 이 또한 휴먼 에러를 발생 시킬 수 있겠죠? 오히려 윗 부분을 안보고 component들 부분만 볼 때 가독성 측면에서 size[1]이라고 하면 그래서 사이즈가 무엇인지 모를 것 같습니다.(물론 코드를 작성한 스스로는 알 수 있죠) 이러한 것들까지 고려되면 좋을 것 같네요. 

2. DOM을 조작하지 않고도 처리하는 방법이 있죠! react native를 다루고 있다보니 현업 react 에서는 어떠한 방법들을 사용하는지 어떤 방법이 가장 좋은 방법인지를 정확히 말씀 드릴 수는 없으나 제 생각에는 modal 관련 라이브러리를 사용하고 있지 않을까 싶습니다. 그리고 그 라이브러리들은 보통 DOM을 조작하지 않고 처리되게 만들어 놓았지 않았을까 싶습니다. 물론 스스로 하드코딩으로 DOM을 조작하지 않고 처리할 수도 있습니다.

3. 그건 뭐가 정답이다라 할 수 없고 DB를 직접 설계하고 만지는 백엔드 분들과 상의를 통해 정하게 됩니다. 결국 ,를 넣어주는 로직이 프론트에서도 처리될 수 있고 백에서 처리될 수도 있기 때문에 그 프로젝트를 진행하는 사람들의 스타일마다 다를 것 같습니다. 저는 현업에서 프론트에서 저런 불필요한 로직을 빼자는 주의여서 백에서 다 ,를 넣은 string으로 저장하던가 그냥 number로 저장했다가 프론트에 데이터 전달할 때는 ,를 찍고 넘겨주거나 하는 방식을 채택하고 있습니다. 하지만 저러한 로직들을 프론트에서 사용할 수 있는 실력은 당연히 갖춰야 하기 때문에 지금 시점에는 최대한 프론트에서도 로직적인 부분을 많이 처리해보시면 좋을 것 같네요!

4. 원래 자기 스스로 짠 코드를 객관적인 시각으로 보기 어렵죠. 저 또한 제 코드를 볼 때 객관적으로 바라보질 못합니다. 하지만 2~3개월 뒤에 내가 이전에 짰던 코드를 보면 리팩토링 해야할 부분들이 많이 보이기도 하죠! 그리고 사람마다, 회사마다 코드 짜는 스타일은 다 다를 수 밖에 없습니다. 그래서 제가 전체적인 코드를 짜는 부분에 관련하여 아무리 리뷰를 드려봤자 이는 제 스타일이고 제가 몸 담고 있는 회사의 스타일의 코드입니다. 저희가 쓰는 코드 스타일이 정답은 아니고 이게 또 제일 최선이라고 볼 수 없습니다.(프로젝트마다 성격과 성향이 다르기 때문에 이 또한 달라질 수 밖에 없기 때문입니다.) 그래서 스스로 보는 안목을 기르기 위해서는 다양한 오픈 소스들을 많이 접해보고 다양한 스타일의 코드 짜는 방법 등 구글링을 통해 다양하게 경험해보면서 사용해보길 권장드립니다. 이후 이전에 내가 짰던 코드들을 보면서 리팩토링 해보기도 하면 좋을 것 같네요. 

이번 과제도 고생 많으셨습니다!

**Comment by hansololiviakim** [comment]
코드 리뷰 다른 레포지토리에서 진행하기로 해 close 합니다!
